import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { ConvexClientProvider } from '@/components/convex-client-provider'
import { ConvexAuthNextjsServerProvider } from '@convex-dev/auth/nextjs/server'
import Modals from '@/components/modals'
import { Toaster } from '@/components/ui/sonner'
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import './globals.css'

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang='en'>
        <head>
          <meta charSet='UTF-8' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <title>Messager</title>
          <meta name='description' content='A simple messaging app built with Convex and Next.js' />
          <meta name='keywords' content='messaging, convex, next.js' />
          <meta property='og:type' content='website' />
          {/* <meta property='og:url' content='https://messager.com' /> */}
          <meta property='og:title' content='Messager' />
          <meta property='og:description' content='A simple messaging app built with Convex and Next.js' />
          <meta
            property='og:image'
            content='https://static.vecteezy.com/system/resources/previews/068/894/567/large_2x/slack-circle-logo-editable-slack-app-for-web-mobile-and-print-projects-free-png.png'
          />
        </head>
        <body className={`${roboto.className} antialiased`}>
          <ConvexClientProvider>
            <Modals />
            <Toaster />
            <NuqsAdapter>{children}</NuqsAdapter>
          </ConvexClientProvider>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  )
}
