import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { ConvexClientProvider } from '@/components/convex-client-provider'
import { ConvexAuthNextjsServerProvider } from '@convex-dev/auth/nextjs/server'
import Modals from '@/components/modals'
import { Toaster } from '@/components/ui/sonner'
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import './globals.css'

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang='en'>
        <body className={`${roboto.className} antialiased`}>
          <ConvexClientProvider>
            <Modals />
            <Toaster />
            <NuqsAdapter>{children}</NuqsAdapter>
          </ConvexClientProvider>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  )
}
